pipeline{
  environment {
  version = "version_$BUILD_NUMBER"
}
  agent {
  label 'dockerlabel'
}
stages {
  stage('checkout') {
    steps {
    git 'https://github.com/swathi431/projDK.git'
    }
  }

  
  stage('docker image') {
     steps {
       script{
        dockerImage = docker.build("swthi31/proj:$version","MyAwesomeApp")
       }
       }
  }
    
}
}
