pipeline{
  environment {
  version = "version_$BUILD_NUMBER"
}
  agent {
  label 'dockerlabel'
}
stages {
  stage('checkout') {
    steps {
      checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/swathi431/CICD.git']]])
    }
  }

  
  stage('docker image') {
     steps {
       script{
        dockerImage = docker.build("swthi31/proj:$version","MyAwesomeApp")
       }
       }
  }
    
}
}
